apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  container:
    - name: app
      image: appleuserfordocker/image
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80