on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: httpd
    steps:
      - uses: actions/checkout@v3 
      
      - name: 'login to dockerhub'
        run: docker login --username ${{ secrets.docker_username }} --password ${{ secrets.docker_token }}
      - name: 'build'
        run: docker build -t ${{ secrets.docker_username }}/image .
      - name: 'push'
        run: docker push ${{ secrets.docker_username }}/image
