on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'list'
        run: ls
      - uses: actions/checkout@v3
      - name: 'list'
        run: ls
        